port: 0
socks-port: 0
redir-port: 0
tproxy-port: 1082
mixed-port: 1080
allow-lan: {openport}
bind-address: '127.0.0.1'
mode: {clashmode}
external-controller: 0.0.0.0:{clash_web_port}
#interface-name: tun114
external-ui: /etc/config/clash/clash-zashboard
secret: {clash_web_password}
log-level: warning
ipv6: false
profile:
  store-fake-ip: true
  store-selected: true
hosts:
    paopaogateway.dns: 127.0.0.1
dns:
  enable: true
  use-hosts: false
  use-system-hosts: false
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: {fake_cidr}
  nameserver:
    - {dns_ip}:{dns_port}#eth0

#mihomo exclude
tls:
external-controller-tls:
external-ui-name:
external-ui-url: "https://invalid.local/update-disabled.zip"
unified-delay: true
tun:
  enable: false
sniffer:
  enable: false
listeners:
find-process-mode: